version: '3.9'

services:
  web:
    image: php:8.3-apache
    container_name: php8.3-apache
    restart: unless-stopped
    ports:
      - "8083:80"  # Web server PHP Apache di port 8083
    volumes:
      - ./app:/var/www/html:ro
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
    environment:
      TZ: "Asia/Jakarta"
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    depends_on:
      - db
    networks:
      - backend
      - frontend
    security_opt:
      - no-new-privileges:true
    read_only: true
    hostname: web

  db:
    image: mariadb:11.3
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3307:3306"  # Ganti port MySQL agar tidak bentrok
    environment:
      MYSQL_ROOT_PASSWORD: "your_root_password"
      MYSQL_DATABASE: "your_database"
      MYSQL_USER: "your_user"
      MYSQL_PASSWORD: "your_password"
      TZ: "Asia/Jakarta"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    hostname: db

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8084:8080"  # Adminer di port 8084
    environment:
      TZ: "Asia/Jakarta"
      ADMINER_DESIGN: pepa
    depends_on:
      - db
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    hostname: adminer

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8085:80"    # HTTP Caddy di 8085
      - "8443:443"   # HTTPS Caddy di 8443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CLOUDFLARE_API_TOKEN: "your_cloudflare_api_token"
    networks:
      - frontend
      - backend
    security_opt:
      - no-new-privileges:true
    read_only: true
    hostname: caddy

networks:
  backend:
    driver: bridge

  frontend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local